---
# defaults file for manila_preconf

# these are the defaults for quotas
manila_instances_num: 100
manila_cores_num: "{{ (manila_instances_num|int)*2 }}"
manila_ram_mb: "{{ (manila_instances_num|int)*2048 }}"
manila_ports_num: "{{ (manila_instances_num|int)*5 }}"
manila_secgroup_num: "{{ (manila_instances_num|int)*1.5|int|abs }}"
manila_secgroup_rule_num: "{{ (manila_secgroup_num|int)*5 }}"
manila_server_groups_num: "{{ ((manila_instances_num|int)*0.5)|int|abs }}"
manila_server_group_member_num: 20

manila_service_image_version: noble
manila_service_image_name: manila-service-image
manila_service_image_id: ""
manila_service_instance_flavor_id: ""
manila_service_instance_password: ""
manila_admin_network_id: ""
manila_admin_subnet_id: ""

manila_service_subnet_cidr: '10.254.0.0/16'
manila_service_subnet_pool_start: '10.254.0.2'
manila_service_subnet_pool_end: '10.254.255.254'
manila_service_subnet_gateway: '10.254.0.1'
