---
# This tasks modifies the quotas for the admin tenant to
# more suitable defaults as the resources for Manila
# are created in the "admin" tenant by default
- name: Fetch the current quotas for the admin tenant
  openstack.cloud.quota:
    name: "{{ admin_project_name | default('admin') }}"
    interface: public
  register: _current_admin_quota

- name: Display the current quota values for the admin tenant
  debug:
    msg:
     - "Current quota value for instances: {{ _current_admin_quota.quotas.compute.instances }}; New quota value for instances: {{ manila_instances_num + _current_admin_quota.quotas.compute.instances }}"
     - "Current quota value for cores: {{ _current_admin_quota.quotas.compute.cores }}; New quota value for cores: {{ manila_cores_num + _current_admin_quota.quotas.compute.cores }}"
     - "Current quota value for server_groups: {{ _current_admin_quota.quotas.compute.server_groups }}; New quota value for server_groups: {{ manila_server_groups_num + _current_admin_quota.quotas.compute.server_groups }}"
     - "Current quota value for ram(MB): {{ _current_admin_quota.quotas.compute.ram }}; New quota value for ram(MB): {{ manila_ram_mb + _current_admin_quota.quotas.compute.ram }}"
     - "Current quota value for ports: {{ _current_admin_quota.quotas.network.ports }}; New quota value for ports: {{ manila_ports_num + _current_admin_quota.quotas.network.ports }}"
     - "Current quota value for security_groups: {{ _current_admin_quota.quotas.network.security_groups }}; New quota value for security_groups: {{ manila_secgroup_num + _current_admin_quota.quotas.network.security_groups }}"
     - "Current quota value for security_group_rules: {{ _current_admin_quota.quotas.network.security_group_rules }}; New quota value for security_group_rules: {{ manila_secgroup_rule_num + _current_admin_quota.quotas.network.security_group_rules }}"
     - "Current quota value for server_group_members: {{ _current_admin_quota.quotas.compute.server_group_members }}; New quota value for server_group_members: {{ manila_server_group_member_num + _current_admin_quota.quotas.compute.server_group_members }}"

- name: modify the quotas for the admin tenant to suit to production environments
  block:
    - openstack.cloud.quota:
        name: "{{ admin_project_name | default('admin') }}"
        instances: "{{ manila_instances_num + _current_admin_quota.quotas.compute.instances }}"
        cores: "{{ manila_cores_num + _current_admin_quota.quotas.compute.cores }}"
        server_groups: "{{ manila_server_groups_num + _current_admin_quota.quotas.compute.server_groups }}"
        ram: "{{ manila_ram_mb + _current_admin_quota.quotas.compute.ram }}"
        port: "{{ manila_ports_num + _current_admin_quota.quotas.network.ports }}"
        security_group: "{{ manila_secgroup_num + _current_admin_quota.quotas.network.security_groups }}"
        security_group_rule: "{{ manila_secgroup_rule_num + _current_admin_quota.quotas.network.security_group_rules }}"
        server_group_members: "{{ manila_server_group_member_num + _current_admin_quota.quotas.compute.server_group_members }}"
        interface: public
  rescue:
    - debug:
        msg: "WARNING: Failed to modify admin tenant quotas! trying to reset to defaults; please review the ansible error logs"
    - name: set the quota to defaults for the admin tenant
      openstack.cloud.quota:
        state: absent
        name: "{{ admin_project_name | default('admin') }}"
        interface: public
