---
# tasks file for manila_preconf

- name: import tasks for modifying the admin tenant quotas
  import_tasks: admin_tenant_quota_setup.yml
  tags:
    - always
    - post_deploy

    ## Claude: Need task to create secrets using ../files/create_manila_k8s_secrets.sh
## If secrets are already there in k8s and/or openstack, they will need deleted
## first.

# One-time create manila-service-network. If the network is already created,
# then it probably should be deleted in openstack and re-created.

- name: import tasks to create manila-service-network for manila
  import_tasks: manila_service_network_setup.yml
  tags:
    - always

# Claude: Create manila-service-image and upload. Please convert playbook to
# task (manila_service_image_builder.yml). It may need to logically split into
# different task files. Make sure to update variables in ../defaults/main.yml
# and/or add new variables to make the playbook (now tasks) work. Currently the
# playbook has some additional logic for "forcing" different behaviors.
# Those force options don't seem to be working and need fixed.

# Claude: after image creation and upload, modify ../templates/manila_default_helm_config.yaml
# by plugging in appropriate values. The service-instance-password should not be
# stored in this file. It should be put into the
# /etc/genestack/helm-configs/global_overrides/secrets.yaml under the
# appropriate yaml hierarchy
# conf:
#   manila:
#     generic:
#       service_instance_password: <manila-service-instance-password>
