---
# These are the tasks to create the security
# groups for Manila as well as health
# manager ports; manila security group includes
# rules for allowing traffic on ports:
# 22
# 111
# 662
# 2049
# 4045
# 20048
# icmp
# health manager secgroup
# only allows traffic on port 5555
#
- name: Create security group for Manila service
  openstack.cloud.security_group:
    name: "{{ manila_service_secgroup_name }}"
    state: present
    description: "security group for Manila"
    interface: public
  register: create_manila_service_secgroup
  until: create_manila_service_secgroup is success
  retries: 5
  delay: 5

- name: Create Security group rule to allow icmp traffic for Manila service
  openstack.cloud.security_group_rule:
    security_group: "{{ create_manila_service_secgroup.security_group.id }}"
    state: present
    protocol: icmp
    remote_ip_prefix: "{{ manila_service_subnet_cidr }}"
    interface: public
  register: manila_service_secgroup_r_icmp
  until: manila_service_secgroup_r_icmp is success
  retries: 5
  delay: 5
  when: manila_icmp_enabled

- name: Create Security group rule to allow ssh traffic for Manila service
  openstack.cloud.security_group_rule:
    security_group: "{{ create_manila_service_secgroup.security_group.id }}"
    state: present
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: "{{ manila_service_subnet_cidr }}"
    interface: public
  register: manila_service_secgroup_r_22
  until: manila_service_secgroup_r_22 is success
  retries: 5
  delay: 5
  when: manila_ssh_enabled

- name: Create security group for Manila Tenants
  openstack.cloud.security_group:
    name: "{{ manila_tenant_secgroup_name }}"
    state: present
    description: "security group for Manila Tenants"
    interface: public
  register: create_manila_tenant_secgroup
  until: create_manila_tenant_secgroup is success
  retries: 5
  delay: 5

- name: Create Security group rule to allow icmp traffic for Manila Tenants
  openstack.cloud.security_group_rule:
    security_group: "{{ create_manila_tenant_secgroup.security_group.id }}"
    state: present
    protocol: icmp
    remote_ip_prefix: "{{ manila_tenant_subnet_cidr }}"
    interface: public
  register: manila_tenant_secgroup_r_icmp
  until: manila_tenant_secgroup_r_icmp is success
  retries: 5
  delay: 5

- name: Create Security group rule to allow ssh traffic for Manila
  openstack.cloud.security_group_rule:
    security_group: "{{ create_manila_tenant_secgroup.security_group.id }}"
    state: present
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: "{{ manila_tenant_subnet_cidr }}"
    interface: public
  register: manila_tenant_secgroup_r_22
  until: manila_tenant_secgroup_r_22 is success
  retries: 5
  delay: 5

- name: Create Security group rule to allow traffic on port 111 for Manila
  openstack.cloud.security_group_rule:
    security_group: "{{ create_manila_tenant_secgroup.security_group.id }}"
    state: present
    protocol: tcp
    port_range_min: 111
    port_range_max: 111
    remote_ip_prefix: "{{ manila_tenant_subnet_cidr }}"
    interface: public
  register: manila_tenant_secgroup_r_111
  until: manila_tenant_secgroup_r_111 is success
  retries: 5
  delay: 5

- name: Create Security group rule to allow traffic on port 662 for Manila
  openstack.cloud.security_group_rule:
    security_group: "{{ create_manila_tenant_secgroup.security_group.id }}"
    state: present
    protocol: tcp
    port_range_min: 662
    port_range_max: 662
    remote_ip_prefix: "{{ manila_tenant_subnet_cidr }}"
    interface: public
  register: manila_tenant_secgroup_r_662
  until: manila_tenant_secgroup_r_662 is success
  retries: 5
  delay: 5

- name: Create Security group rule to allow traffic on port 2049 for Manila
  openstack.cloud.security_group_rule:
    security_group: "{{ create_manila_tenant_secgroup.security_group.id }}"
    state: present
    protocol: tcp
    port_range_min: 2049
    port_range_max: 2049
    remote_ip_prefix: "{{ manila_tenant_subnet_cidr }}"
    interface: public
  register: manila_tenant_secgroup_r_2049
  until: manila_tenant_secgroup_r_2049 is success
  retries: 5
  delay: 5

- name: Create Security group rule to allow traffic on port 4045 for Manila
  openstack.cloud.security_group_rule:
    security_group: "{{ create_manila_tenant_secgroup.security_group.id }}"
    state: present
    protocol: tcp
    port_range_min: 4045
    port_range_max: 4045
    remote_ip_prefix: "{{ manila_tenant_subnet_cidr }}"
    interface: public
  register: manila_tenant_secgroup_r_4045
  until: manila_tenant_secgroup_r_4045 is success
  retries: 5
  delay: 5

- name: Create Security group rule to allow traffic on port 20048 for Manila
  openstack.cloud.security_group_rule:
    security_group: "{{ create_manila_tenant_secgroup.security_group.id }}"
    state: present
    protocol: tcp
    port_range_min: 20048
    port_range_max: 20048
    remote_ip_prefix: "{{ manila_tenant_subnet_cidr }}"
    interface: public
  register: manila_tenant_secgroup_r_20048
  until: manila_tenant_secgroup_r_20048 is success
  retries: 5
  delay: 5

- name: Create Security group rule to allow traffic on port 111 UDP for Manila
  openstack.cloud.security_group_rule:
    security_group: "{{ create_manila_tenant_secgroup.security_group.id }}"
    state: present
    protocol: udp
    port_range_min: 111
    port_range_max: 111
    remote_ip_prefix: "{{ manila_tenant_subnet_cidr }}"
    interface: public
  register: manila_tenant_secgroup_r_111_udp
  until: manila_tenant_secgroup_r_111_udp is success
  retries: 5
  delay: 5

- name: Create Security group rule to allow traffic on port 662 UDP for Manila
  openstack.cloud.security_group_rule:
    security_group: "{{ create_manila_tenant_secgroup.security_group.id }}"
    state: present
    protocol: udp
    port_range_min: 662
    port_range_max: 662
    remote_ip_prefix: "{{ manila_tenant_subnet_cidr }}"
    interface: public
  register: manila_tenant_secgroup_r_662_udp
  until: manila_tenant_secgroup_r_662_udp is success
  retries: 5
  delay: 5

- name: Create Security group rule to allow traffic on port 2049 UDP for Manila
  openstack.cloud.security_group_rule:
    security_group: "{{ create_manila_tenant_secgroup.security_group.id }}"
    state: present
    protocol: udp
    port_range_min: 2049
    port_range_max: 2049
    remote_ip_prefix: "{{ manila_tenant_subnet_cidr }}"
    interface: public
  register: manila_tenant_secgroup_r_2049_udp
  until: manila_tenant_secgroup_r_2049_udp is success
  retries: 5
  delay: 5

- name: Create Security group rule to allow traffic on port 4045 UDP for Manila
  openstack.cloud.security_group_rule:
    security_group: "{{ create_manila_tenant_secgroup.security_group.id }}"
    state: present
    protocol: udp
    port_range_min: 4045
    port_range_max: 4045
    remote_ip_prefix: "{{ manila_tenant_subnet_cidr }}"
    interface: public
  register: manila_tenant_secgroup_r_4045_udp
  until: manila_tenant_secgroup_r_4045_udp is success
  retries: 5
  delay: 5

- name: Create Security group rule to allow traffic on port 20048 UDP for Manila
  openstack.cloud.security_group_rule:
    security_group: "{{ create_manila_tenant_secgroup.security_group.id }}"
    state: present
    protocol: udp
    port_range_min: 20048
    port_range_max: 20048
    remote_ip_prefix: "{{ manila_tenant_subnet_cidr }}"
    interface: public
  register: manila_tenant_secgroup_r_20048_udp
  until: manila_tenant_secgroup_r_20048_udp is success
  retries: 5
  delay: 5

- name: Create security group for health manager ports
  openstack.cloud.security_group:
    name: "{{ manila_health_mgr_secgroup_name }}"
    state: present
    description: "security group for health manager ports"
    interface: public
  register: create_manila_health_mgr_secgroup
  until: create_manila_health_mgr_secgroup is success
  retries: 5
  delay: 5

- name: Create Security group rule to allow traffic on port 5555 for health manager
  openstack.cloud.security_group_rule:
    security_group: "{{ create_manila_health_mgr_secgroup.security_group.id }}"
    state: present
    protocol: udp
    port_range_min: 5555
    port_range_max: 5555
    interface: public
  register: manila_health_mgr_secgroup_r1
  until: manila_health_mgr_secgroup_r1 is success
  retries: 5
  delay: 5

- name: Create Security group rule to allow traffic on port 555 UDP for Manila Tenants
  openstack.cloud.security_group_rule:
    security_group: "{{ create_manila_tenant_secgroup.security_group.id }}"
    state: present
    protocol: udp
    port_range_min: 5555
    port_range_max: 5555
    remote_ip_prefix: "{{ manila_tenant_subnet_cidr }}"
    interface: public
  register: manila_tenant_secgroup_r_5555_udp
  until: manila_tenant_secgroup_r_5555_udp is success
  retries: 5
  delay: 5


