---
# These are the tasks for creating health_mgr
# ports for manila; the ports are created with
# a shell script as the ansible modules currently
# don't support all the required params for creating
# ports
- name: Obtain the UUID of the manila-service-net
  openstack.cloud.networks_info:
    name: manila-service-net
    interface: public
  register: manila_service_info

- name: Obtain the UUID of the manila tenant secgroup
  openstack.cloud.security_group_info:
    name: "{{ manila_tenant_secgroup_name }}"
    interface: public
  register: manila_tenant_secgroup_info

- name: run the shell script to create worker ports if required
  script:
    cmd: create_worker_ports.sh {{ manila_service_info.networks[0].id }} {{ manila_tenant_secgroup_info.security_groups[0].id }} {{ lookup('env', 'OS_CLOUD') | default('openstack_helm') }}
    creates: /tmp/manila_worker_controller_ip_port_list
