---
# These are the tasks to setup the manila-mgmt-net and
# subnet for Manila; this can either be a vlan, flat
# or a geneve or vxlan network
- name: Create manila-mgmt-net for the Manila
  openstack.cloud.network:
    name: manila-mgmt-net
    state: present
    provider_network_type: "{{ manila_mgmt_net_type }}"
    provider_physical_network: "{{ manila_mgmt_net_physical_net | default(omit) }}"
    provider_segmentation_id: "{{ manila_mgmt_net_segmentation_id | default(omit) }}"
    interface: public
  register: create_manila_mgmt_net
  until: create_manila_mgmt_net is success
  retries: 5
  delay: 5

- name: Create subnet for manila-mgmt-net
  openstack.cloud.subnet:
    name: manila-mgmt-subnet
    state: present
    enable_dhcp: true
    cidr: "{{ manila_mgmt_subnet_cidr }}"
    allocation_pool_start: "{{ manila_mgmt_subnet_pool_start }}"
    allocation_pool_end: "{{ manila_mgmt_subnet_pool_end }}"
    disable_gateway_ip: true
    network_name: manila-mgmt-net
    interface: public
  register: create_manila_mgmt_subnet
  until: create_manila_mgmt_subnet is success
  retries: 5
  delay: 5

# Bit of a hack to ensure gateway is disabled until ansible-playbook releases the fix..
# disabling the gateway works on 'updates' as-is but not on creates yet..
- name: Update subnet for lb-mgmt-net
  openstack.cloud.subnet:
    name: lb-mgmt-subnet
    state: present
    enable_dhcp: true
    cidr: "{{ lb_mgmt_subnet_cidr }}"
    allocation_pool_start: "{{ lb_mgmt_subnet_pool_start }}"
    allocation_pool_end: "{{ lb_mgmt_subnet_pool_end }}"
    disable_gateway_ip: true
    network_name: lb-mgmt-net
    interface: public
  register: create_lb_mgmt_subnet
  until: create_lb_mgmt_subnet is success
  retries: 5
  delay: 5
